name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on: ubuntu-latest # Specify the runner environment
    steps:
      #- uses: actions/checkout@v3 # Check out the repository code
      - name: Run Shell Command
        run: |
          echo "Hello from GitHub Actions!"
          echo ${{PATH}}
          ls -l # List files in the current directory

  
